product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }
    
product_menu:
    path:     /menu
    defaults: { _controller: ProductBundle:Default:menu }
    
product_basket:
    path:     /basket
    defaults: { _controller: ProductBundle:Default:basket }
    
product_add:
    path:     /add_product
    defaults: { _controller: ProductBundle:Default:addProduct }
    
category_add:
    path:     /add_category
    defaults: { _controller: ProductBundle:Default:addCategory }
    
ingredient_add:
    path:     /add_ingredient
    defaults: { _controller: ProductBundle:Default:addIngredient }
        
basket_add:
    path:     /add_to_basket/{id}
    defaults: { _controller: ProductBundle:Default:addToBasket }
    requirements:
        id: \d+