product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }
    
product_menu:
    path:     /menu
    defaults: { _controller: ProductBundle:Default:menu }
    
product_basket:
    path:     /basket
    defaults: { _controller: ProductBundle:Basket:basket }
    
product_add:
    path:     /add_product
    defaults: { _controller: ProductBundle:Default:addProduct }
    
category_add:
    path:     /add_category
    defaults: { _controller: ProductBundle:Default:addCategory }
    
ingredient_add:
    path:     /add_ingredient
    defaults: { _controller: ProductBundle:Default:addIngredient }
        
basket_add:
    path:     /add_to_basket/{id}
    defaults: { _controller: ProductBundle:Basket:addToBasket }
    requirements:
        id: \d+

emeal_order:
    path:     /order
    defaults: { _controller: ProductBundle:Order:myOrder }
   
emeal_order_all:
    path:     /all_order
    defaults: { _controller: ProductBundle:Order:allOrder }
    
emeal_order_add:
    path:     /order_add
    defaults: { _controller: ProductBundle:Order:orderAdd }
    
not_found:
    path:     /not_found
    defaults: { _controller: ProductBundle:Default:notFound }