<?php

namespace ProductBundle\Repository;

/**
 * eMealOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eMealOrderRepository extends \Doctrine\ORM\EntityRepository
{
    
    
}
